import Feed from "@/components/Feed";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Head from "next/head";

export default function Home() {
	return (
		<div className="min-h-screen bg-[#F3F2EF] dark:bg-black">
			<Head>
				<title>LinkedIn App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="mx-auto mt-24 flex min-h-screen max-w-6xl gap-x-6 pl-4">
				<SideBar />
				<Feed />
				<div className="h-screen w-[29%] bg-red-300"></div>
			</main>
		</div>
	);
}
