import Feed from "@/components/Feed";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Modal from "@/components/Modal";
import { useRecoilState } from "recoil";
import { modalState, modalTypeState } from "@/atoms/modalAtom";
import { AnimatePresence } from "framer-motion";

export default function Home() {
	const router = useRouter();
	const [modalOpen, setModalOpen] = useRecoilState(modalState);
	const [modalType, setModalType] = useRecoilState(modalTypeState);

	const { status } = useSession({
		required: true,
		onUnauthenticated() {
			// The user is not authenticated, handle it here.
			router.push("/home");
		},
	});

	return (
		<div className="relative min-h-screen bg-[#F3F2EF] dark:bg-black">
			<Head>
				<title>LinkedIn App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<AnimatePresence>
				{modalOpen && (
					<Modal
						type={modalType}
						handleClose={() => setModalOpen(false)}
					/>
				)}
			</AnimatePresence>

			<main className="mx-auto flex min-h-screen max-w-6xl gap-x-6 pt-24 pl-4 dark:bg-black">
				<SideBar />
				<Feed />
				<div className="h-screen w-[29%] bg-red-300"></div>
			</main>
		</div>
	);
}
